dist: xenial
language: go
env:
  - GOFLAGS='-mod vendor'

go:
  - 1.x

git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

script:
  - go test -v ./...  # Run all the tests
